### ISSUE TITLE
Pool Opening Notes

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#98]
When adding notes to bottom of pool opening, notes box moves up and you are unable to see what you are typing (when using hardware keyboard)

**Comment by Treverr** [comment]
Fixed. Disabled the adjustment for now, unless needed.

**Comment by rcasad** [comment]
Adjustment is needed, notes still cannot be seen when typing with a software keyboard. Hardware keyboard seems to be working fine
